package com.tuan.amazon.utilities;

public class Constants {
    public static final String KEY_COLLECTION_USERS = "users";
    public static final String KEY_NAME = "name";
    public static final String KEY_EMAIL = "email";
    public static  final String KEY_USER_ID = "userId";
    public static final String KEY_USER_IMAGE = "userImage";
    public static final String KEY_FRIEND = "friend";
    public static final String KEY_LMKB = "lờiMờiKếtBạn";
    public static final String KEY_GD = "bạnGửiLờiMờiĐến";
    public static final String KEY_NG = "aiĐóGửiĐếnBạnLờiMời";
    public static final String KEY_ID = "ID";
    public static final String KEY_YOUR_FRIENDS = "yourFriends";
    public static final String KEY_PERSONAL_INFORMATION = "personalInformation";
    public static final String KEY_NOI_O = "noiO";
    public static final String KEY_HOME_TOWN = "homeTown";
    public static final String KEY_NOI_LAM_VIEC = "noiLamViec";
    public static final String KEY_MOI_QUAN_HE = "moiQUANHE";
    public static final String KEY_CONG_KHAI_NOI_O = "congKhaiNoiO";
    public static final String KEY_CONG_KHAI_HOME_TOWN = "congKhaiHomeTown";
    public static final String KEY_CONG_KHAI_NOI_LAM_VIEC = "congKhaiNoiLamViec";
    public static final String KEY_USER_PROFILE = "userProfile";
    public static final String KEY_CDCK_CONG_KHAI = " Công khai ";
    public static final String KEY_CDCK_BAN_BE = " Bạn bè ";
    public static final String KEY_CDCK_MINH_TOI = " Chỉ mình tôi ";
    public static final String KEY_PREFERENCE_NAME = "preference";
    public static final String KEY_CHECK_CHAT_FROM_PP = "checkChat";
    public static final String KEY_CHAT_MESSAGE = "chatMessage";
    public static final String KEY_SENDER_ID = "senderId";
    public static final String KEY_RECEIVER_ID = "receiverId";
    public static final String KEY_TIME_SEND = "timeSend";
    public static final String KEY_CONVERSATION = "conversation";
    public static final String KEY_LAST_MESSAGE = "lastMessage";
    public static final String KEY_SENDER_NAME = "senderName";
    public static final String KEY_SENDER_IMAGE = "senderImage";
    public static final String KEY_RECEIVER_NAME = "receiverName";
    public static final String KEY_RECEIVER_IMAGE = "receiverImage";
//    public static final String KEY_CONVERSATION_ID = "conversationId";
//    public static final String KEY_CONVERSATION_IMAGE = "conversationImage";
//    public static final String KEY_CONVERSATION_NAME = "conservationName";
    public static final String KEY_POSTS = "posts";
    public static final String KEY_CREATOR_ID = "creatorId";
    public static final String KEY_CAPTION = "caption";
    public static final String KEY_TIME_CREATE_POST = "timeCreatePost";
    public static final String KEY_IMAGE_POST = "imagePost";
}